#!/bin/sh
set -e

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
cd "$SCRIPT_DIR"

if [ "$(uname -s 2>/dev/null)" = "Darwin" ] && [ "$(uname -m 2>/dev/null)" = "x86_64" ]; then
  PKG_CONFIG_PATH_DEFAULTS=
  for d in /usr/local/opt/freetype/lib/pkgconfig /usr/local/opt/libpng/lib/pkgconfig; do
    [ -d "$d" ] || continue
    case ":${PKG_CONFIG_PATH:-}:" in
      *":$d:"*) ;;
      *) PKG_CONFIG_PATH_DEFAULTS="${PKG_CONFIG_PATH_DEFAULTS:+$PKG_CONFIG_PATH_DEFAULTS:}$d" ;;
    esac
  done
  if [ -n "$PKG_CONFIG_PATH_DEFAULTS" ]; then
    if [ -n "${PKG_CONFIG_PATH:-}" ]; then
      PKG_CONFIG_PATH="$PKG_CONFIG_PATH_DEFAULTS:$PKG_CONFIG_PATH"
    else
      PKG_CONFIG_PATH="$PKG_CONFIG_PATH_DEFAULTS"
    fi
    export PKG_CONFIG_PATH
  fi
fi

if [ -z "${FREETYPE_CFLAGS:-}" ] && command -v pkg-config >/dev/null 2>&1; then
  FREETYPE_CFLAGS=$(pkg-config --cflags freetype2 2>/dev/null || true)
fi
if [ -z "${FREETYPE_LIBS:-}" ] && command -v pkg-config >/dev/null 2>&1; then
  FREETYPE_LIBS=$(pkg-config --libs freetype2 2>/dev/null || true)
fi

BUILD_ENV_FILE=${BUILD_ENV_FILE:-build.env}
BUILD_ENV_NEEDED=
if [ -n "${WINE_BUILD_SUFFIX:-}" ] || [ -n "${ENABLE_DXMT:-}" ] || [ -n "${DXMT_DIR:-}" ] || \
  [ -n "${DXMT_MESON:-}" ] || [ -n "${DXMT_NATIVE_LLVM_PATH:-}" ] || \
  [ -n "${DXMT_WINE_BUILD_PATH:-}" ] || [ -n "${DXMT_WINE_BUILTIN_DLL:-}" ] || \
  [ -n "${FREETYPE_CFLAGS:-}" ] || [ -n "${FREETYPE_LIBS:-}" ]; then
  BUILD_ENV_NEEDED=1
fi

if [ -n "$BUILD_ENV_NEEDED" ]; then
  {
    echo "# Generated by configure_release.sh. Edit as needed."
    [ -n "${WINE_BUILD_SUFFIX:-}" ] && printf "WINE_BUILD_SUFFIX = %s\n" "$WINE_BUILD_SUFFIX"
    [ -n "${ENABLE_DXMT:-}" ] && printf "ENABLE_DXMT = %s\n" "$ENABLE_DXMT"
    [ -n "${DXMT_DIR:-}" ] && printf "DXMT_DIR = %s\n" "$DXMT_DIR"
    [ -n "${DXMT_MESON:-}" ] && printf "DXMT_MESON = %s\n" "$DXMT_MESON"
    [ -n "${DXMT_NATIVE_LLVM_PATH:-}" ] && printf "DXMT_NATIVE_LLVM_PATH = %s\n" "$DXMT_NATIVE_LLVM_PATH"
    [ -n "${DXMT_WINE_BUILD_PATH:-}" ] && printf "DXMT_WINE_BUILD_PATH = %s\n" "$DXMT_WINE_BUILD_PATH"
    [ -n "${DXMT_WINE_BUILTIN_DLL:-}" ] && printf "DXMT_WINE_BUILTIN_DLL = %s\n" "$DXMT_WINE_BUILTIN_DLL"
    [ -n "${FREETYPE_CFLAGS:-}" ] && printf "FREETYPE_CFLAGS = %s\n" "$FREETYPE_CFLAGS"
    [ -n "${FREETYPE_LIBS:-}" ] && printf "FREETYPE_LIBS = %s\n" "$FREETYPE_LIBS"
  } > "$BUILD_ENV_FILE"
fi

if [ "${ENABLE_DXMT:-0}" = "1" ]; then
  echo "configure_release.sh: ENABLE_DXMT=1 only writes DXMT settings to build.env; run ./integrate_dxmt.sh to build and install DXMT DLLs." >&2
fi

CFLAGS=${CFLAGS:-"-O2 -g0"}
CXXFLAGS=${CXXFLAGS:-"-O2 -g0"}
export CFLAGS CXXFLAGS
[ -n "${FREETYPE_CFLAGS:-}" ] && export FREETYPE_CFLAGS
[ -n "${FREETYPE_LIBS:-}" ] && export FREETYPE_LIBS

# Recreate configure flags from config.status (release build).
exec ./configure \
  --enable-win64 \
  --with-vulkan \
  --disable-wow64 \
  --without-x
